
package gnu.x11.keysym;


/**
 * Vietnamese-specific keyboard symbols. Imported from
 * <code>XK_VIETNAMESE</code> section of
 * <code>/usr/include/X11/keysymdef.h</code>. Note that byte 3(0x1e. 
 */
public enum Vietnamese {
   ABELOWDOT(0x1ea0),
   ABELOWDOT_SMALL(0x1ea1),
   AHOOK(0x1ea2),
   AHOOK_SMALL(0x1ea3),
   ACIRCUMFLEXACUTE(0x1ea4),
   ACIRCUMFLEXACUTE_SMALL(0x1ea5),
   ACIRCUMFLEXGRAVE(0x1ea6),
   ACIRCUMFLEXGRAVE_SMALL(0x1ea7),
   ACIRCUMFLEXHOOK(0x1ea8),
   ACIRCUMFLEXHOOK_SMALL(0x1ea9),
   ACIRCUMFLEXTILDE(0x1eaa),
   ACIRCUMFLEXTILDE_SMALL(0x1eab),
   ACIRCUMFLEXBELOWDOT(0x1eac),
   ACIRCUMFLEXBELOWDOT_SMALL(0x1ead),
   ABREVEACUTE(0x1eae),
   ABREVEACUTE_SMALL(0x1eaf),
   ABREVEGRAVE(0x1eb0),
   ABREVEGRAVE_SMALL(0x1eb1),
   ABREVEHOOK(0x1eb2),
   ABREVEHOOK_SMALL(0x1eb3),
   ABREVETILDE(0x1eb4),
   ABREVETILDE_SMALL(0x1eb5),
   ABREVEBELOWDOT(0x1eb6),
   ABREVEBELOWDOT_SMALL(0x1eb7),
   EBELOWDOT(0x1eb8),
   EBELOWDOT_SMALL(0x1eb9),
   EHOOK(0x1eba),
   EHOOK_SMALL(0x1ebb),
   ETILDE(0x1ebc),
   ETILDE_SMALL(0x1ebd),
   ECIRCUMFLEXACUTE(0x1ebe),
   ECIRCUMFLEXACUTE_SMALL(0x1ebf),
   ECIRCUMFLEXGRAVE(0x1ec0),
   ECIRCUMFLEXGRAVE_SMALL(0x1ec1),
   ECIRCUMFLEXHOOK(0x1ec2),
   ECIRCUMFLEXHOOK_SMALL(0x1ec3),
   ECIRCUMFLEXTILDE(0x1ec4),
   ECIRCUMFLEXTILDE_SMALL(0x1ec5),
   ECIRCUMFLEXBELOWDOT(0x1ec6),
   ECIRCUMFLEXBELOWDOT_SMALL(0x1ec7),
   IHOOK(0x1ec8),
   IHOOK_SMALL(0x1ec9),
   IBELOWDOT(0x1eca),
   IBELOWDOT_SMALL(0x1ecb),
   OBELOWDOT(0x1ecc),
   OBELOWDOT_SMALL(0x1ecd),
   OHOOK(0x1ece),
   OHOOK_SMALL(0x1ecf),
   OCIRCUMFLEXACUTE(0x1ed0),
   OCIRCUMFLEXACUTE_SMALL(0x1ed1),
   OCIRCUMFLEXGRAVE(0x1ed2),
   OCIRCUMFLEXGRAVE_SMALL(0x1ed3),
   OCIRCUMFLEXHOOK(0x1ed4),
   OCIRCUMFLEXHOOK_SMALL(0x1ed5),
   OCIRCUMFLEXTILDE(0x1ed6),
   OCIRCUMFLEXTILDE_SMALL(0x1ed7),
   OCIRCUMFLEXBELOWDOT(0x1ed8),
   OCIRCUMFLEXBELOWDOT_SMALL(0x1ed9),
   OHORNACUTE(0x1eda),
   OHORNACUTE_SMALL(0x1edb),
   OHORNGRAVE(0x1edc),
   OHORNGRAVE_SMALL(0x1edd),
   OHORNHOOK(0x1ede),
   OHORNHOOK_SMALL(0x1edf),
   OHORNTILDE(0x1ee0),
   OHORNTILDE_SMALL(0x1ee1),
   OHORNBELOWDOT(0x1ee2),
   OHORNBELOWDOT_SMALL(0x1ee3),
   UBELOWDOT(0x1ee4),
   UBELOWDOT_SMALL(0x1ee5),
   UHOOK(0x1ee6),
   UHOOK_SMALL(0x1ee7),
   UHORNACUTE(0x1ee8),
   UHORNACUTE_SMALL(0x1ee9),
   UHORNGRAVE(0x1eea),
   UHORNGRAVE_SMALL(0x1eeb),
   UHORNHOOK(0x1eec),
   UHORNHOOK_SMALL(0x1eed),
   UHORNTILDE(0x1eee),
   UHORNTILDE_SMALL(0x1eef),
   UHORNBELOWDOT(0x1ef0),
   UHORNBELOWDOT_SMALL(0x1ef1),
   YBELOWDOT(0x1ef4),
   YBELOWDOT_SMALL(0x1ef5),
   YHOOK(0x1ef6),
   YHOOK_SMALL(0x1ef7),
   YTILDE(0x1ef8),
   YTILDE_SMALL(0x1ef9),
   OHORN(0x1efa), /* u+01a0 */
   OHORN_SMALL(0x1efb), /* u+01a1 */
   UHORN(0x1efc), /* u+01af */
   UHORN_SMALL(0x1efd), /* u+01b0 */

   COMBINING_TILDE(0x1e9f), /* u+0303 */
   COMBINING_GRAVE(0x1ef2), /* u+0300 */
   COMBINING_ACUTE(0x1ef3), /* u+0301 */
   COMBINING_HOOK(0x1efe), /* u+0309 */
   COMBINING_BELOWDOT(0x1eff); /* u+0323 */

   private int code;
   
   public int getCode() {
       return this.code;
   }
   
   Vietnamese(int code) {
       this.code = code;
   }
}
